option_industries = [
            "Agriculture, forestry and fishing",
            "Mining and quarrying",
            "Manufacturing",
            "Electricity, gas, steam and air conditioning supply",
            "Water supply; sewerage, waste management and remediation activities",
            "Construction",
            "Wholesale and retail trade; repair of motor vehicles and motorcycles",
            "Transportation and storage",
            "Accommodation and food service activities",
            "Information and communication",
            "Financial and insurance activities",
            "Real estate activities",
            "Professional, scientific and technical activities",
            "Administrative and support service activities",
            "Public administration and defence; compulsory social security",
            "Education",
            "Human health and social work activities",
            "Arts, entertainment and recreation",
            "Other service activities",
            "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use",
            "Activities of extraterritorial organisations and bodies",
            "Industry unknown",
    ]

industry_dict = {
        "A": "Agriculture, forestry and fishing",
        "B": "Mining and quarrying",
        "C": "Manufacturing",
        "D": "Electricity, gas, steam and air conditioning supply",
        "E": "Water supply; sewerage, waste management and remediation activities",
        "F": "Construction",
        "G": "Wholesale and retail trade; repair of motor vehicles and motorcycles",
        "H": "Transportation and storage",
        "I": "Accommodation and food service activities",
        "J": "Information and communication",
        "K": "Financial and insurance activities",
        "L": "Real estate activities",
        "M": "Professional, scientific and technical activities",
        "N": "Administrative and support service activities",
        "O": "Public administration and defence; compulsory social security",
        "P": "Education",
        "Q": "Human health and social work activities",
        "R": "Arts, entertainment and recreation",
        "S": "Other service activities",
        "T": "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use",
        "U": "Activities of extraterritorial organisations and bodies",
    }

municipality_and_region_info_fields = [
            "Inhabitants, total",
            "Agriculture, forestry and fishing",
            "Mining and quarrying",
            "Manufacturing",
            "Electricity, gas, steam and air conditioning supply",
            "Water supply; sewerage, waste management and remediation activities",
            "Construction",
            "Wholesale and retail trade; repair of motor vehicles and motorcycles",
            "Transportation and storage",
            "Accommodation and food service activities",
            "Information and communication",
            "Financial and insurance activities",
            "Real estate activities",
            "Professional, scientific and technical activities",
            "Administrative and support service activities",
            "Public administration and defence; compulsory social security",
            "Education",
            "Human health and social work activities",
            "Arts, entertainment and recreation",
            "Other service activities",
            "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use",
            "Activities of extraterritorial organisations and bodies",
            "Employed",
            "Workplaces, total",
]
